Neos:
  ContentRepositoryRegistry:
    contentRepositories:
      node_templates:
        preset: default
        contentDimensions: []
        userIdProvider:
          factoryObjectName: Neos\ContentRepository\BehavioralTests\TestSuite\Behavior\FakeUserIdProviderFactory
        clock:
          factoryObjectName: Neos\ContentRepository\BehavioralTests\TestSuite\Behavior\FakeClockFactory

  Neos:
    sites:
      'node-templates-site':
        uriPathSuffix: '.html'
        contentRepository: node_templates
        contentDimensions:
          resolver:
            factoryClassName: Neos\Neos\FrontendRouting\DimensionResolution\Resolver\AutoUriPathResolverFactory
